/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_API_URL: process.env.NEXT_API_URL,
    DATABASE_URL: process.env.DATABASE_URL,
    NEXT_API_PORT: process.env.NEXT_API_PORT,
    NEXT_CORS_PORT_ORIGIN: process.env.NEXT_CORS_PORT_ORIGIN,
    NEXT_FORMAT_DATE_MOMENT: process.env.NEXT_FORMAT_DATE_MOMENT,
    NEXT_TIME_ZONE: process.env.NEXT_TIME_ZONE,
    NEXT_AUTH_EMAIL: process.env.NEXT_AUTH_EMAIL,
    NEXT_AUTH_PASSWORD: process.env.NEXT_AUTH_PASSWORD,
    NEXT_JWT_SECRET: process.env.NEXT_JWT_SECRET,
    NEXT_PROMOCION_NAME: process.env.NEXT_PROMOCION_NAME,
    NEXT_EMAIL_SERVICE: process.env.NEXT_EMAIL_SERVICE,
    NEXT_EMAIL_SENDER: process.env.NEXT_EMAIL_SENDER,
    NEXT_EMAIL_SENDER_PASSWORD: process.env.NEXT_EMAIL_SENDER_PASSWORD,
    NEXT_EMAIL_RECIVER: process.env.NEXT_EMAIL_RECIVER,
    NEXT_PROMOTION_MAX_USERS_LIMIT: process.env.NEXT_PROMOTION_MAX_USERS_LIMIT ? process.env.NEXT_PROMOTION_MAX_USERS_LIMIT : undefined,
    NEXT_PROMOTION_START_DATE: process.env.NEXT_PROMOTION_START_DATE ? process.env.NEXT_PROMOTION_START_DATE : undefined,
    NEXT_PROMOTION_FINISH_DATE: process.env.NEXT_PROMOTION_FINISH_DATE ? process.env.NEXT_PROMOTION_FINISH_DATE : undefined
  }
};

module.exports = nextConfig;
