import styles from '@/styles/style.scss';

export const metadata = {
  title: 'Prueba de next',
  description: 'Generated by Next.js'
};

const RootLayout = ({ children }) => {
  return (
    <html lang='es'>
      <body className={styles.backgroundImage}>{children}</body>
    </html>
  );
};

export default RootLayout;
